### PR TITLE
feat(templates): add React Native templates

### PR DESCRIPTION
**Pull request by samouss**
The PR adds a "React InstantSearch Native" template that use `react-instantsearch-native`.

- The template don't handle `attributesForFacetting` it's a bit hard to implement because there is a lots of condition. The code is a bit more complicated than the web in order to have a RefinementList
- In case we don't provide `mainAttribute` the `Highlight` file is generated but unused

simulator screen shot - iphone x - 2018-06-13 at 19 21 11

### CODE REVIEW

**Comment by francoischalifour** [comment]
One thing to note is that although this template will be released in the [`templates`](https://github.com/algolia/create-instantsearch-app/tree/templates) branch, it won't be available on CodeSandbox.

Could we offer a similar experience with React Native? With Expo?

**Comment by Haroenv** [comment]
seems like it's possible: https://forums.expo.io/t/modules-available-in-snack/1651/16

**Comment by francoischalifour** [comment]
Can it be loaded from a GitHub URL?

**Comment by samouss** [comment]
Yes it would be nice but at least the template is available from the CLI.

**Pull request merged**
