### PR TITLE
refactor(templates): Declare search clients outside of components

### PR DESCRIPTION
**Pull request by francoischalifour**

### CODE REVIEW

**Comment by samouss** [comment]
Why we do not update the InstantSearch one?

**Comment by francoischalifour** [comment]
Originally because `searchClient` is compatible since InstantSearch.js 2.8.0. It's only a matter of time. I think we can go ahead.

**Comment by samouss** [comment]
But we have the same issue with Angular right?

**Comment by francoischalifour** [comment]
Angular InstantSearch 2.0.0 also changes the components' names (we dropped `ng-`), so we already don't support version 1.

**Pull request merged**
