### PR TITLE
docs(readme): Add screencast

### PR DESCRIPTION
**Pull request by francoischalifour**
Steps to recreate this animated SVG:

- Install `asciinema`: `brew install asciinema`
- If you get the error `ModuleNotFoundError: No module named 'pkg_resources'`, run `brew postinstall python3`
- Then, start recording your terminal session (I use [Fish](https://fishshell.com/)): `asciinema rec -c "/usr/local/bin/fish -l" -t "Create InstantSearch App"`
- If you have errors with your `locale`, run something like `set -x LC_ALL en_US.UTF-8` (Fish command, use `export` if you use Bash)
- It generated this screencast: https://asciinema.org/a/oYteqikQba9E814Op2bWdvID7
- Then, install `svg-term-cli`: `yarn global add svg-term-cli`
- Convert the screencast to an animated SVG: `svg-term --cast=oYteqikQba9E814Op2bWdvID7 --out screencast.svg --window`

### CODE REVIEW

**Comment by samouss** [comment]
We can try to optimise a bit the SVG the one on Create React App is only 64KB. When I open the README.md on GitHub the scroll is a bit laggy.

**Comment by francoischalifour** [comment]
I'm not sure how to do it since it's already compressed. The solution I see is to remove some tags in the installation process but it's quite hard not to break anything.

**Comment by Haroenv** [comment]
looks a bit sad on Safari 
screen shot 2018-06-29 at 14 14 56

A possibility is to use just the placeholder

**Comment by francoischalifour** [comment]
@Haroenv You mean just a screenshot?

**Comment by francoischalifour** [comment]
Closing in favor of #70.

**Pull request closed without merging**
